name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^9.2.13

  path_provider: ^2.0.2
  permission_handler: ^6.0.1
  path: ^1.6.4
  intl: ^0.17.0
  google_speech: ^2.1.2
  record_mp3: ^3.0.0
  flutter_ffmpeg: ^0.4.2
  dart_openai: ^1.9.1
  text_to_speech: ^0.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/